project:
  type: website
  output-dir: docs

website:
  bread-crumbs: false
  sidebar: 
    contents:
      - text: Home
        href: index.qmd
      - section: Stock assessment tutorials
        contents:
        - text: Model convergence diagnostics
          href: assessment/diagnostics.qmd
        - section: ADMB
          contents:
          - text: Jitter test
            href: assessment/ADMB_jitter.qmd
          - text: Likelihood profile

format:
  html:
    page-layout: full
    css: "https://qfcatmsu.github.io/assets/quarto/qfc_styles.css"
    toc: true
    toc-title: Contents
    toc-location: left
    fig-align: left
    theme: default
    fontsize: 15px
    number-sections: true
    grid: 
      body-width: 1000px
    include-in-header:
      - text: |
          <script>mod=true;</script>
          <script src="https://qfcatmsu.github.io/assets/quarto/qfc_styles.js"></script>



