project:
  type: website
  output-dir: website/docs

website:
  bread-crumbs: false
  sidebar: 
    contents:
      - text: Home
        href: index.qmd
      - text: Equilibrium reference points
        href: website/eq_recruitment/equil_recruit.qmd
      - section: Model convergence diagnostics
        contents:
        - text: Model convergence checklist
          href: website/convergence/conv_diagnostics.qmd
        - section: Instructions for ADMB
          contents:
          - text: Jitter test
            href: website/convergence/ADMB_jitter.qmd
          - text: Likelihood profile
            href: website/convergence/ADMB_likelihood.qmd

format:
  html:
    page-layout: full
    # css: "https://qfcatmsu.github.io/assets/quarto/qfc_styles.css"
    toc: true
    toc-title: Contents
    toc-location: left
    fig-align: left
    theme: default
    fontsize: 15px
    number-sections: true
    grid: 
      body-width: 1000px
    # include-in-header:
    #   - text: |
    #       <script>mod=true;</script>
    #       <script src="https://qfcatmsu.github.io/assets/quarto/qfc_styles.js"></script>



