project:
  type: website
  output-dir: docs

website:
  title: "Stock assessment tutorials"
  bread-crumbs: false
  sidebar: 
    contents:
      - text: Home
        file: index.qmd
      - section: Guides
        contents:
        - text: Model convergence and diagnostics
          href: guides/diagnostics.qmd
#  navbar:
 #   left:
  #    - href: index.qmd
   #     text: Home
    #  - text: Guides
     #   menu:
          # - text: Introduction to RTMB
          #   href: guides/rtmb_intro.qmd
      #    - text: Model convergence and diagnostics
       #     href: guides/diagnostics.qmd
      # - text: Concepts
      #   menu: 
      #     - text: Selectivity
      #       href: notes/selectivity.qmd

format:
  html:
    page-layout: full
  #  theme: cosmo
    css: "https://qfcatmsu.github.io/assets/quarto/qfc_styles.css"
    toc: true
    toc-title: Contents
    toc-location: left
    fig-align: left
    theme: default
    fontsize: 15px
    number-sections: true
    grid: 
      body-width: 1000px
    include-in-header:
      - text: |
          <script>mod=true;</script>
          <script src="https://qfcatmsu.github.io/assets/quarto/qfc_styles.js"></script>



