project:
  type: website
  output-dir: docs

website:
  title: "Stock assessment tutorials"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Guides
        menu:
          # - text: Introduction to RTMB
          #   href: guides/rtmb_intro.qmd
          - text: Model convergence and diagnostics
            href: guides/diagnostics.qmd
      # - text: Concepts
      #   menu: 
      #     - text: Selectivity
      #       href: notes/selectivity.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



