---
title: "Selectivity"
format:
  html:
    toc: true
    page-layout: full
    css: styles.css
editor: visual
---

## Definition of selectivity

**Selectivity**: relative vulnerability of a demographic group of the fished population to capture by a fishery or survey, with at least one demographic group being fully selected (Cadrin et al., 2015). 

Selectivity is a combination of two processes:

- the relative probability of capture for a demographic group (i.e., *contact selectivity*; Miller and Fryer, 1999)
- proportion of the group that is available to the fishery in time and space (i.e., *population selectivity*; Miller and Fryer, 1999)
  - aka *vulnerability*

Assessments models typically require a particular form of selection curve and estimates a population selectivity curve. Selectivity is used to link observed composition data to model predictions about population abundance-at-age/-size. If multiple gear types operate in the fishery, or if the catch-at-age compositions from different segments of the fleet have distinct characteristics, then the catch-at-age data can be partitioned into separate matrices for each gear or fleet type with separate selectivity curves and parameters for each type. 

### Selectivity and fishing mortality - separability

Selectivity is the portion of a demographic group that is vulnerable to capture by fishing:

$$ 
F_{t,a} = F_t s_a
$$ {#eq-1}

- $F_t$ is fishing mortality at time $t$ for fully-vulnerable ages (i.e., a year-specific fishing mortality multiplier)
  - typically managed through limiting total fishing effort in a year 
- $s_a$ is the selectivity of the age group
  - typically managed by regulating fishing technology and behavior

This definition is typically used for age-structure population models, but the same equation can be related to any other demographic groups (e.g., size intervals, life history stages). [Eq @eq-1] quantifies either constant or average selectivity during the time interval. The function expressed in [eq @eq-1] is termed *separability* because $F_{t,a}$ can be separated into the components $F_t$ and $s_a$.

Recall that catchability ($q$) is the effect of of a unit of fishing effort ($E$) directed on the population, with the effect measured as the exponential rate of fishing mortality imposed on the population over a time interval $t$:

$$
F_t = q E_t
$$ {#eq-2}

Considering that catchability and selectivity have a relationship with fishing mortality, [Eq @eq-1] & [-@eq-2] can be combined:

$$
F_{t,a} = s_a q E_t; \hspace{4mm} q_a = s_a  q
$$ {#eq-3}

Selectivity then plays an essential role as a component of the survival equation in abundance at age:

$$
N_{t,a} = N_{t-1,a-1}e^{-(F_{t-1} s_{a-1} + M_{t-1,a-1})}
$$ {#eq-4}

- $N_{t,a}$ is the abundance of survivors of an age class at the end of year $t$

[Eq @eq-4] is the primary process equation for all age-structured stock assessment models. 


## Selectivity functions

There are several forms of fishing selectivity. Sampson and Scott (2012) defined four categories:

1. Asymptotic: the oldest age classes are fully vulnerable
  1a. Knife-edged: the simplest form of asymptotic form
2. Increasing: selection increases with age
3. Saddle: there is at least one local minimum selection in the intermediate range of age classes
4. Domed: the age for maximum selectivity ($s = 1$) is imtermediate in the range of age classes

<!-- differentiability -->

### Logistic

Asymptotic selectivity is often modeled using a logistic function. There are many variations of the logistic selectivity function. 

$$
s_a = \dfrac{1}{1 + exp(-\sigma_s (a - a_{50}))}
$$ 

- $\sigma_s$ is the logistic slope parameter
- $a_{50}$ is the age of 50% vulnerability to the fishery (i.e., $s_{a_{50}} = 0.5$)

Another parameterization of logistic selectvity uses parameters $a_{50}$ and $a_{95}$, which represent the ages where a fish has a probability 50% or 95% chance of being captured. 

$$
s_a = \dfrac{1}{1+exp\left( -log(19)\left(\dfrac{a - a_{50}}{a_{95} - a_{50}}\right) \right)}
$$

::: {.callout-note collapse="true"}
## Why log(19)?
 We need to ensure that the logistic function equals 0.95 when $a = a_{95}$ and equals 0.5 when $a = a_{50}$. Think about the odds of being captured:

 - The exponent of the log odds equals the odds ratio
 - The odds ratio is the probability of an event (i.e., getting captured) happening over the probablity of it not happening

 Thus, the log-odds ratio for the age at which we have a 95% probability of getting captured is $log(\dfrac{0.95}{0.05})$. This can be rewritten as $log(\dfrac{19/20}{1/20})$, which then simplifies to $log(19)$.

 This is not necesssary for $a_{50}$ because the odds ratio of two events with 50% probability is equal to zero. 
:::

### Double logistic

The six parameter version of the double normal selectivity function can capture both asymptotic and dome-shaped shapes (commonly used in Stock Synthesis; Methot and Wetzel, 2013). The double normal has three components connected by steep logistic "joiners" to provide overall differentiability:

$$
s_a = {asc}_a (1-j_{1,a}) + j_{1,a}((1-j_{2,a}) + j_{2,a} {dsc}_a)
$$

- ${asc}_a$ is the ascending limb 

$$
{asc}_a = p_5 + (1-p_5)\left(e^{-(a - p_1)^2 / e^{p_3}} - e^{{p_1}^2 / e^{p_3}} \right) / \left(1 - e^{{p_1}^2 / e^{p_3}} \right)
$$

- ${dsc}_a$ is the descending limb

$$
{dsc}_a = 1 + (p_6 - 1)\left(e^{-(a - \gamma)^2 / e^{p_4}} - 1 \right) / \left(e^{-(A-\gamma)^2 / e^{p_4}} - 1 \right)
$$

- $j_{1,a}$ is the first joiner function

$$
j_{1,a} = \dfrac{1}{\left(1+e^{-20(a-p_1)/(1+|a-p_1|)}\right)}
$$

- $j_{2,a}$ is the second joiner function

$$
j_{2,a} = \dfrac{1}{\left(1+e^{-20(a-\gamma)/(1+|a-\gamma|)}\right)}
$$

- $p_1$ is the age at which selectivity=1 starts
- $\gamma$ is the age at which selecitivity=1 ends and is defined as:

$$
\gamma = p_1 + 1 + \left ( \dfrac{0.99 A - p_1 - 1}{1 + e^{-p_2}} \right)
$$

- $p_2$ determines the age at which selectivity=1 ends (the width of the "top"; $\gamma$ is the end point)
- $p_3$ determines the slope of the ascending section
- $p_4$ determines the slope of the descending section
- $p_5$ is the selectivity at age 0 (in logit-space)
- $p_6$ is the selectivity at age $A$ (in logit-space)

The double normal can mimic the asymptotic selectivity function by setting $p_6 = 1$.

### Gamma

Dome-shaped selectivity can be represented using a gamma function:
$$
s_a = \dfrac{a}{a_{max}}^{a_{max}/p} e^{(a_{max}-a)/p}; \hspace{6mm} p = 0.5 \left[\sqrt{{a_{max}}^2 + 4\gamma^2}- a_{max}\right]
$$

- $a_{max}$ is the full vulnerability to the fishery (i.e., $s_{a_{max}}$ = 1)
- $\gamma$ is the gamma slope parameter


## Sensitivities of selectivity
The form of selectivity is assumed in various stock assessment models. $F_{t,a}$ can either be directly estimated or derived from estimated paramters.

- Catch curve
  - Estimates total mortatliy as the negative of log-linear slope in [eq @eq-4] by assuming full selectiivty for a range of ages, usually from a middle age to oldest age (i.e., knife-edge selectivity)
  - Chapman and Robson, 1960
- Virtual population analysis (VPA)
  - Assumes the selectivity of oldest age relative to a younger age to estimate $N_{t,a}$ to derive $F_{t,a}$
  - Selectivity in the most recent year is similar to previous years
  - Age range of full vulnerability is often assumed to derive $F_t$ (i.e., knife-edge selectivity)
  - Shepherd and Pope, 2002
- Statistical catch at age (SCAA)
  - Separability ([eq @eq-1]) - estimate a time series of $F_t$ and selectivity ($s_a$), either as estimated parameters or derived from functional selectivity functions
  - Maunder and Punt, 2013

<!-- Assuming dome-shaped selectivity could imply that a considerable portion of the population was "cryptic". The population estimates of older fish are not proportional to those observed through sampling efforts (i.e., essentially unobservable by the fishery or surveys). -->

## References

Cadrin, S.X., DeCelles, G.R. and Reid, D. (2016). Informing fishery assessment and management with field observations of selectivity and efficiency. Fisheries Research, 184, 9-17.

Chapman, D., & Robson, D. S. (1960). The analysis of a catch curve. Biometrics, 354-368.

Maunder, M. N., & Punt, A. E. (2013). A review of integrated analysis in fisheries stock assessment. Fisheries research, 142, 61-74.

Methot Jr, R. D., & Wetzel, C. R. (2013). Stock synthesis: a biological and statistical framework for fish stock assessment and fishery management. Fisheries Research, 142, 86-99.

Millar, R. B., & Fryer, R. J. (1999). Estimating the size-selection curves of towed gears, traps, nets and hooks. Reviews in Fish Biology and Fisheries, 9, 89-116.

Sampson, D. B., & Scott, R. D. (2012). An exploration of the shapes and stability of population–selection curves. Fish and Fisheries, 13(1), 89-104.

Shepherd, J. G., & Pope, J. G. (2002). Dynamic pool models I: Interpreting the past using Virtual Population Analysis. Handbook of Fish Biology and Fisheries: Fisheries, 2, 127-163.